import 'package:mockito/annotations.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'mocks.mocks.dart'; // This file is generated by build_runner

// Mockito creates mock versions of the follow classes
@GenerateMocks([FirebaseAuth, User, QuerySnapshot, QueryDocumentSnapshot])
void main() {}
