// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXNyWhSHkJGp1lCNE8W7lIZBk1_R0vm24',
    appId: '1:448797205170:web:d51c4f28083e789a3c5fab',
    messagingSenderId: '448797205170',
    projectId: 'mood-waves',
    authDomain: 'mood-waves.firebaseapp.com',
    storageBucket: 'mood-waves.appspot.com',
    measurementId: 'G-D2254S2G26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKjEQ8S7HDrD27NsC7Z-zSWf5jb6orByk',
    appId: '1:448797205170:android:b93db119d3db67513c5fab',
    messagingSenderId: '448797205170',
    projectId: 'mood-waves',
    storageBucket: 'mood-waves.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKEJ_XrgLUvnlR_XFxQ_gtlf1DUIU40HU',
    appId: '1:448797205170:ios:fe0ad617b3fef6183c5fab',
    messagingSenderId: '448797205170',
    projectId: 'mood-waves',
    storageBucket: 'mood-waves.appspot.com',
    iosBundleId: 'com.example.moodWaves',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKEJ_XrgLUvnlR_XFxQ_gtlf1DUIU40HU',
    appId: '1:448797205170:ios:1a32dcd16574ab6a3c5fab',
    messagingSenderId: '448797205170',
    projectId: 'mood-waves',
    storageBucket: 'mood-waves.appspot.com',
    iosBundleId: 'com.example.moodWaves.RunnerTests',
  );
}
